[package]
name = "{{ prefix_name }}_{{ suffix_name }}_core"
version.workspace = true
edition.workspace = true

[dependencies]
{% if persistence ~= 'None' %}{{ prefix_name }}_{{ suffix_name }}_persistence = { path = "../{{ prefix_name }}_{{ suffix_name }}_persistence" }
{% endif %}{% if cache ~= 'None' %}{{ prefix_name }}_{{ suffix_name }}_cache = { path = "../{{ prefix_name }}_{{ suffix_name }}_cache" }
{% endif %}{% if messaging ~= 'None' %}{{ prefix_name }}_{{ suffix_name }}_messaging = { path = "../{{ prefix_name }}_{{ suffix_name }}_messaging" }
{% endif %}
anyhow = "1"
prost = "0.13"
serde = { version = "1", features = ["derive"] }
tonic = "0.12"
tracing = "0.1"

[build-dependencies]
tonic-build = "0.12"
